<?php

namespace App\Http\Resources;

use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

/**
 * Resource for class progression tables.
 *
 * Wraps the progression table data generated by ClassProgressionTableGenerator.
 * Provides type information for OpenAPI documentation.
 *
 * @property array<array{key: string, label: string, type: string}> $columns Table column definitions
 * @property array<array<string, mixed>> $rows Table rows with level data
 */
class ProgressionTableResource extends JsonResource
{
    /**
     * Transform the resource into an array.
     *
     * @return array{
     *   columns: array<ProgressionColumnResource>,
     *   rows: array<ProgressionRowResource>
     * }
     */
    public function toArray(Request $request): array
    {
        return [
            /** @var array<ProgressionColumnResource> */
            'columns' => ProgressionColumnResource::collection(collect($this->resource['columns'])),
            /** @var array<ProgressionRowResource> */
            'rows' => ProgressionRowResource::collection(collect($this->resource['rows'])),
        ];
    }
}
